config/routes.rb
Rails.application.routes.draw do

  resources :reservations, only: [:index, :create, :destroy]

  root 'reservations#index'

end

app/models/destination.rb
# == Schema Information
#
# Table name: destinations
#
#  id         :integer          not null, primary key
#  departure  :string
#  arrival    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Destination < ActiveRecord::Base
  has_many :teleporters
  validates :departure, presence: true, uniqueness: true
  validates :arrival, presence: true, uniqueness: true

  def full_desination
    "#{departure} - #{arrival}"
  end
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id            :integer          not null, primary key
#  name          :string
#  teleporter_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Reservation < ActiveRecord::Base
  belongs_to :teleporter
  validates :name, presence: true

  def outdated?
   self.remaining <= 0
  end

  def remaining
    ((self.created_at + 1.hour) - Time.now).to_i / 60
  end

end

app/models/teleporter.rb
# == Schema Information
#
# Table name: teleporters
#
#  id             :integer          not null, primary key
#  destination_id :integer
#  capacity       :integer          default(3)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Teleporter < ActiveRecord::Base
  belongs_to :destination
  has_many :reservations

  validates :capacity, presence: true, numericality: {greater_than: 0}

  def departure_available?
    (reservations.count) < self.capacity
  end

  def remaining_seats
    (capacity - reservations.count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :check_name_duplicate, only: [:create]
  before_action :clear_outdated

  def index
    @teleporters = Teleporter.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to reservations_path, notice: 'Votre réservation a bien été enregistrée'
    else
      redirect_to reservations_path, alert: 'une erreur est survenue'
    end
  end

  def destroy
    @reservation = Reservation.find_by(id: params[:id])
    @reservation.destroy
    redirect_to reservations_path, notice: 'Votre réservation à bien été annulée'
  end

  private
  def clear_outdated
    reservations = Reservation.all

    reservations.each do |r|
      r.destroy if r.outdated?
    end
  end

  def check_name_duplicate
    check_name =  Reservation.find_by(name: params[:reservation][:name])
    return redirect_to reservations_path, alert: 'Le nom est déjà utilisé pour un téléporteur'   if check_name.present?

  end

  def reservation_params
    params.require(:reservation).permit(:name, :teleporter_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blueorigins
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
      %a.navbar-brand{:href => "#"} BlueOrigin
      %a.nav-link{:href => "#"}

    .container
      = yield

app/views/reservations/_form.html.haml
= form_for Reservation.new, html: {class: 'form-inline', role: 'form'} do |f|
  = f.hidden_field :teleporter_id, value: teleporter.id
  .form-group
    = f.text_field :name, placeholder: 'Name', class: 'form-control', required: true
  = f.submit "Réservation", class: 'form-control btn btn-outline-primary'

app/views/reservations/_teleporter.html.haml
.row.teleporter
  .row
    .col-md-12
      %h3= teleporter.destination.full_desination
      %p= "Il reste #{teleporter.remaining_seats} place(s)"

  .row
    .col-md-12
      - if teleporter.departure_available?
        = render partial: 'form', locals: {teleporter: teleporter}
      - else
        .alert.alert-danger
          Vous devez attendre qu'une place se libère
      %table.table
        %thead
          %tr
            %th Nom du passager
            %th Heure du départ
            %th Vous pourriez utiliser le téléporteur dans
            %th Annuler la réservation
        %tbody
          - teleporter.reservations.each do |d|
            %tr
              %td= d.name
              %td= d.created_at.strftime('%m/%e/%y à %H:%M')
              %td= "#{d.remaining} min"
              %td= button_to 'Annuler', reservation_path(d), method: :delete, class: 'btn btn-outline-danger'
%hr/

app/views/reservations/create.html.haml
%h1 Reservations#create
%p Find me in app/views/reservations/create.html.haml

app/views/reservations/index.html.haml
.row
  .col-md-12
    %p.lead.center
      Bienvenue Dans la réservation express.
  .col-md-12
    %h2 reservation
    - if notice
      .alert.alert-success
        = notice
    - if alert
      .alert.alert-danger
        = alert
    - @teleporters.each do |teleporter|
      = render partial: 'teleporter', locals: {teleporter: teleporter}

app/views/reservations/show.html.haml
%h1 Reservations#show
%p Find me in app/views/reservations/show.html.haml